apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blue
spec:
  replicas: 4 # Increased for better visibility of the roll-out
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       # Create 1 extra pod above the replica count during update
      maxUnavailable: 0 # Ensure all 4 pods are always available during update
  selector:
    matchLabels:
      app: messaging
      version: blue
  template:
    metadata:
      labels:
        app: messaging
        version: blue
    spec:
      containers:
      - name: django
        image: your-docker-username/django-messaging-app:2.0
        ports:
        - containerPort: 8000